# Generated by Django 6.1 on 2026-09-19 05:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('modified', 'Modified'), ('rejected', 'Rejected'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('epss_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_cisa_kev', models.BooleanField(default=False)),
                ('priority_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_modified_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_in_feed_at', models.DateTimeField(blank=True, null=True)),
                ('nvd_raw_json', models.JSONField(blank=True, default=dict)),
                ('kev_raw_json', models.JSONField(blank=True, default=dict)),
                ('epss_raw_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-priority_score', 'cve_id'],
                'indexes': [models.Index(fields=['status'], name='intel_vuln_status_idx'), models.Index(fields=['is_cisa_kev'], name='intel_vuln_kev_idx'), models.Index(fields=['priority_score'], name='intel_vuln_priority_idx'), models.Index(fields=['last_modified_at'], name='intel_vuln_modified_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cvss_score__gte', 0), ('cvss_score__lte', 10)), ('cvss_score__isnull', True), _connector='OR'), name='intel_vuln_cvss_range'), models.CheckConstraint(condition=models.Q(models.Q(('epss_score__gte', 0), ('epss_score__lte', 1)), ('epss_score__isnull', True), _connector='OR'), name='intel_vuln_epss_range'), models.CheckConstraint(condition=models.Q(('priority_score__gte', 0), ('priority_score__isnull', True), _connector='OR'), name='intel_vuln_priority_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityAIEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=150)),
                ('prompt_version', models.CharField(max_length=50)),
                ('input_hash', models.CharField(max_length=128)),
                ('summary_text', models.TextField(blank=True)),
                ('remediation_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latest_enrichment', to='intel.vulnerability')),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='intel_ai_status_idx'), models.Index(fields=['generated_at'], name='intel_ai_generated_idx')],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_vendor', models.CharField(max_length=255)),
                ('raw_product', models.CharField(max_length=255)),
                ('normalized_vendor', models.CharField(max_length=255)),
                ('normalized_product', models.CharField(max_length=255)),
                ('source_cpe', models.TextField(blank=True)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('ambiguous', 'Ambiguous'), ('ignored', 'Ignored')], default='unmatched', max_length=20)),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='intel.vulnerability')),
            ],
            options={
                'ordering': ['normalized_vendor', 'normalized_product', 'id'],
                'indexes': [models.Index(fields=['normalized_product'], name='intel_vuln_prod_norm_prod_idx'), models.Index(fields=['normalized_vendor', 'normalized_product'], name='intel_vuln_prod_norm_look_idx'), models.Index(fields=['match_status'], name='intel_vuln_prod_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('vulnerability', 'normalized_vendor', 'normalized_product'), name='intel_vuln_product_unique_normalized')],
            },
        ),
    ]
