# Generated by Django 6.1 on 2026-08-09 18:20

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TechTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("category", models.CharField(choices=[("product", "Product")], max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TechTagAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=160)),
                ("normalized_alias", models.CharField(editable=False, max_length=160)),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="taxonomy.techtag"),
                ),
            ],
            options={
                "ordering": ["alias"],
            },
        ),
        migrations.CreateModel(
            name="UserTechTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="user_assignments", to="taxonomy.techtag"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="selected_tech_tags", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["user__email", "tag__name"],
            },
        ),
        migrations.AddConstraint(
            model_name="techtag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="taxonomy_techtag_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="techtagalias",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("alias"),
                name="taxonomy_techtagalias_alias_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="techtagalias",
            constraint=models.UniqueConstraint(fields=("normalized_alias",), name="taxonomy_techtagalias_normalized_alias_unique"),
        ),
        migrations.AddConstraint(
            model_name="usertechtag",
            constraint=models.UniqueConstraint(fields=("user", "tag"), name="taxonomy_usertechtag_user_tag_unique"),
        ),
    ]
