# Generated by Django 6.1 on 2026-09-19 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techtag',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
