# Generated by Django 6.1 on 2026-09-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run_type', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('backfill', 'Backfill')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_degraded', models.BooleanField(default=False)),
                ('degraded_reason', models.TextField(blank=True)),
                ('nvd_count', models.PositiveIntegerField(default=0)),
                ('kev_count', models.PositiveIntegerField(default=0)),
                ('epss_count', models.PositiveIntegerField(default=0)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('digest_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='ingestion_run_status_idx'), models.Index(fields=['started_at'], name='ingestion_run_started_idx')],
            },
        ),
    ]
