# Generated by Django 6.1 on 2026-09-19 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('intel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest_date', models.DateField()),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('matching_vulnerability_count', models.PositiveIntegerField(default=0)),
                ('backfill_vulnerability_count', models.PositiveIntegerField(default=0)),
                ('rendered_subject', models.CharField(blank=True, max_length=255)),
                ('rendered_html', models.TextField(blank=True)),
                ('rendered_text', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_digests', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-digest_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyDigestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('is_backfill', models.BooleanField(default=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('cve_id', models.CharField(max_length=32)),
                ('severity_label', models.CharField(blank=True, max_length=32)),
                ('cvss_base_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('epss_probability', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('is_kev', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_remediation', models.TextField(blank=True)),
                ('daily_digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='digests.dailydigest')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to='intel.vulnerability')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailSendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider', models.CharField(default='resend', max_length=64)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('daily_digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_attempts', to='digests.dailydigest')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailydigest',
            constraint=models.UniqueConstraint(fields=('organization', 'digest_date'), name='unique_daily_digest_per_org_date'),
        ),
        migrations.AddConstraint(
            model_name='dailydigestitem',
            constraint=models.UniqueConstraint(fields=('daily_digest', 'rank'), name='unique_digest_rank'),
        ),
        migrations.AddConstraint(
            model_name='dailydigestitem',
            constraint=models.UniqueConstraint(fields=('daily_digest', 'vulnerability'), name='unique_vulnerability_per_digest'),
        ),
    ]
