# Generated by Django 6.1 on 2026-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydigestitem',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
