# Generated by Django 6.1 on 2026-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0002_dailydigestitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydigestitem',
            name='date_label',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
