# Generated by Django 6.1 on 2026-09-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digests', '0003_dailydigestitem_date_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsendattempt',
            old_name='failure_reason',
            new_name='error_message',
        ),
        migrations.AddField(
            model_name='emailsendattempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='emailsendattempt',
            constraint=models.UniqueConstraint(fields=('daily_digest', 'attempt_number'), name='unique_send_attempt_number_per_digest'),
        ),
    ]
